#!/usr/bin/env bash
# Bash script that will display information about subdomains

print_domain()
{
    echo -n "The subdomain $2"
    dig "$2.$1" | grep "$2.$1." |
    awk '{ print " is a " $4 " record and points to " $5 }' |
    tail -1
}

if [ "$2" ]; then
    print_domain "$1" "$2"
else
    print_domain "$1" www
    print_domain "$1" lb-01
    print_domain "$1" web-01
    print_domain "$1" web-02
fi
