#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server;/a error_page 404 /404.html; location = /404.html {root /usr/share/nginx/html;internal;}' /etc/nginx/sites-available/default
sudo service nginx restart
