#!/usr/bin/env bash
# A Bash script that pings an IP address passed as an argument
key="$1"
if [ -z "$key" ]
  then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$key"
fi
