#!/usr/bin/env bash
# Bash script that use the content in the file /etc/passwd.
while IFS=: read -r name password id g_id info home cmd
do
	echo "The user $name is part of the $g_id gang, lives in $home and rides $cmd. $id's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
