#!/usr/bin/env bash
# Displays Holberton School 10 times, at the 9th iteration, it displays Hi after
x=0
while [ $x -lt 10 ];
do
    echo "Holberton School"
    (( x++ ));
    if [ $x -eq 9 ]
    then
	echo "Hi"
    fi
done
