#!/usr/bin/env bash
#  Run Nginx as Nginx
pkill apache2
chown nginx: /etc/nginx/nginx.conf
sudo chmod 600 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
