#!/usr/bin/env bash
#  Run Nginx as Nginx
pkill apache2
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
chown nginx: /etc/nginx/nginx.conf
sudo chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
